CREATE TABLE question(
id INT AUTO_INCREMENT,
title VARCHAR(200) UNIQUE NOT NULL,
option_1 VARCHAR(200) UNIQUE NOT NULL,
option_2 VARCHAR(200) UNIQUE NOT NULL,
option_3 VARCHAR(200) UNIQUE NOT NULL,
option_4 VARCHAR(200) UNIQUE NOT NULL,
PRIMARY KEY(id)
);


CREATE TABLE answers(
id INT AUTO_INCREMENT,
user_id INT NOT NULL,
question_id INT NOT NULL,
selected_option INT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (question_id) REFERENCES question(id)
);

